### ISSUE TITLE
Missing variables in .env under "Steps to run locally"

### ISSUE THREAD

**Issue by BID-UW** [benlikescode/geohub#102]
I am trying to run locally and have followed the instructions, but there seems to be variables missing.  I get an error for missing "LOCAL_MONGO" and Sendgrid API "API key does not start with "SG."

Could someone post a working .env file ?

**Comment by eirrw** [comment]
In https://github.com/benlikescode/geohub/blob/main/backend/utils/dbConnect.ts#L21 the app checks if it is running in a production environment or not (as specified by the current Node environment). For local dev (i.e. `yarn dev`) the correct environment variable is `LOCAL_MONGO`, whereas `MONGO_URI` is correct for production (`yarn start`). This should probably be updated in the docs.

The sendgrid API is just a warning, and AFAIK only matters if you want to send emails (which I think is *only* used in the "forgot password" functionality). If you want to use it, you'll need to set `SENDGRID_API_KEY` to your API key from SendGrid.
