### ISSUE TITLE
Provide docker container with docker compose template for easy local setup

### ISSUE THREAD

**Issue by sibbl** [benlikescode/geohub#11]
Yes, the local setup is already quite easy.

But only having to add the Google Maps key to a docker compose template and then just running "docker compose up" or running it as a Portainer stack would be even easier.

I'd appreciate it, if this docker compose template as well as a prebuilt docker container would be available. The container could be built via a GitHub action and be hosted at ghcr as part of this repository.

PS: awesome project! Thanks for building it ♥️

**Comment by benlikescode** [comment]
I will add this as a nice to have. I am not too familiar with Docker so would gladly welcome a PR for this. 

Thanks and glad you like it!

**Comment by tabishnaqvi1311** [comment]
Hey, I'd like to work on this issue!

**Comment by Paillat-dev** [comment]
I might do this if I have time

**Comment by Paillat-dev** [comment]
@benlikescode Is there any directory where content is stored apart from the database? Knowing that would help me much!
