### ISSUE TITLE
Photographic Negative of the images in Google Street View is displayed 

### ISSUE THREAD

**Issue by ramankumar-1** [benlikescode/geohub#114]
While playing the World - Singleplayer game on Microsoft Edge browser (Version 130.0.2849.80 (Official build) (64-bit)), **Photographic Negative of the images** is being displayed. 

Screenshot added below. 

![image](https://github.com/user-attachments/assets/0baefa3f-8c26-4eac-af9d-06f91e8f3f6c)

**Comment by benlikescode** [comment]
Thanks for creating an issue, but this is actually expected behavior once the Google Maps API daily limit is reached. 

This is explained in detail [here](https://github.com/benlikescode/geohub?tab=readme-ov-file#-faq).
