### ISSUE TITLE
bug: page reloads and loses some progress

### ISSUE THREAD

**Issue by asallay** [benlikescode/geohub#12]
The game simply reloads every 10-15 minutes, and although it continues my current session, it moves me back to the initial starting point for the current landmark, so I have to start 'moving' from the beginning again.

Also: in the 45 minutes I've played, Safari told me the page ran out of memory and it had to reload the page.

**Comment by benlikescode** [comment]
Thanks for the feedback and sorry for the late reply. I merged a few PRs recently that should improve the game performance. Hopefully that will help with the memory issue and refreshing of the game.

Maybe another solution/nice to have, would be a checkpoint button that saves your current location you have moved to. Let me know what you think and I will add this to the roadmap!
