### ISSUE TITLE
GeoHub mentioned by mapper after deleting ADW from GeoGuessr

### ISSUE THREAD

**Issue by nitro2k01** [benlikescode/geohub#20]
Recently, [mapper announced that they would delete their Geoguessr account](https://docs.google.com/spreadsheets/d/1hNGFglJcKlH3GQYnPByRM5bpBbxpCIir_bbdDt00soI/edit?pli=1#gid=1015484280) and all associated maps including A Diverse World, in protest of the direction that GeoGuessr has taken recently. In this same post, mapper also mentioned GeoHub as an alternative to GeoGuessr. I don't know if they've been in contact with you directly, but if not, this is something you may want to be aware of.

**Comment by benlikescode** [comment]
Thanks for letting me know, awesome to see it being promoted by Mapper!
