### ISSUE TITLE
Feature request: link to the Github from the Vercel instance, and/or other contact info

### ISSUE THREAD

**Issue by nitro2k01** [benlikescode/geohub#21]
I'm noticing that there seems to be no contact info easily available on the official Vercel instance of GeoHub. It may be desireable to have some way of contacting you and/or a link to the GitHub page so people can more easily find the source code and post issues.

**Comment by benlikescode** [comment]
This is a great idea! I will release an update soon with links to this repo and create a few other socials

**Comment by benlikescode** [comment]
GitHub and Discord links have been added! (they are at the bottom of the sidebar)
