### ISSUE TITLE
Feature request: investigate integration with ReAnna's map-making app.

### ISSUE THREAD

**Issue by nitro2k01** [benlikescode/geohub#23]
ReAnna made an [alternative map editor for GeoGuessr](https://map-making.app/). Investigate supporting this in some capacity in GeoHub, for example through an officially supported import/export script.

**Comment by benlikescode** [comment]
Interesting, looks like a good tool. If I understand correctly, you want the ability to import/export on GeoHub's map tool so you can move locations between the two?

**Comment by nitro2k01** [comment]
For example, or discuss some other solution with ReAnna. It also exposes some hidden functionality in GeoGuessr, namely the ability to either specify a specific panorama (old date of capture) or an auto-updating location. Not sure if GeoHub would support this atm.
