### ISSUE TITLE
Feature request: add a city guesser game mode

### ISSUE THREAD

**Issue by The24thDS** [benlikescode/geohub#28]
It would be amazing for Geohub to also have a version of the city guessing game available at https://virtualvacation.us/guess including the multiplayer part. I played the multiplayer a lot when it was still working and it was a lot of fun.

Let me know what you think about the idea and maybe we can work together to see it implemented.

**Comment by benlikescode** [comment]
Could be a cool addition! Any idea on how to get the videos?

**Comment by The24thDS** [comment]
VirtualVacation is using youtube videos, We would probably have to pick up some videos manually, more or less. I know that https://www.youtube.com/@poptravelorg/videos has a lot of walking around videos so we could start with that.
We could also allow users to submit videos that once approved will have a chance to show.
