### ISSUE TITLE
Changing the map's language

### ISSUE THREAD

**Issue by Noxian16** [benlikescode/geohub#38]
Would it be possible to implement a way to change the language the map is displayed in? The map in Geoguessr is in English for me and so is the one on my Google account, but in Geohub it's in my native language, which can make getting the right city difficult as a lot of cities/towns (even small ones) in neighboring countries have very different names from their native forms, unlike in English.

**Comment by benlikescode** [comment]
Interesting, the map package I am using seems to use your browsers language by default. 

I could add a toggle in the user settings to use English or your browser language. I would want to get more feedback on this to determine if it should just be set to English by default.

For now, I would just recommend changing your browser language to English.
