### ISSUE TITLE
create-daily-challenge endpoint has no auth

### ISSUE THREAD

**Issue by ilya-zlobintsev** [benlikescode/geohub#39]
Currently anyone can create a new daily challenge by going to the `create-daily-challenge` endpoint. While it won't reset the leaderboard for today, it does reset the challenge itself.

It should probably be fixed ASAP before people abuse it.

**Comment by benlikescode** [comment]
You're right, thanks for reporting this!

**Comment by ilya-zlobintsev** [comment]
Are you sure the fix didn't break anything? Because it does not look like the challenge has been reset today (2023-07-23)

**Comment by benlikescode** [comment]
Thanks again, it should be good now! I will spend some time later cleaning up the leaderboard to reflect the proper challenges 😅

**Comment by benlikescode** [comment]
Leaderboard should be back to normal now. Winner for 2023-07-23 should show up in about 5 hours
