### ISSUE TITLE
Option to use Mapillary Free Street View

### ISSUE THREAD

**Issue by gabrielrbarbosa** [benlikescode/geohub#58]
If anyone is interested in testing Mapillary JS in this project
I've made a simple example how to consume Mapillary API and filter by 360 cameras to avoid cellphone low quality street view.

https://github.com/gabrielrbarbosa/MapillaryGeoGuessr

This would solve google maps API pricing since it allows a lot more requests: "Requests to graph.mapillary.com are limited to 50,000 per minute per app." [API Docs](https://www.mapillary.com/developer/api-documentation)

**Comment by benlikescode** [comment]
Cool, thanks for sharing! I don't plan on adding Mapillary to GeoHub at this point but I will keep this in mind if I ever do. 

Just a heads up, the next round wasn't automatically showing after each guess (had to refresh the page).
