### ISSUE TITLE
Question about map locations

### ISSUE THREAD

**Issue by Ptorioo** [benlikescode/geohub#61]
Just a simple question regarding to the map locations. Since you mentioned the locations are public from the Geoguessr API on reddit, I am wondering how do you extract locations from popular maps like A Community World (I suppose it is some sort of .json)? Because I'm trying to build a similar tool myself.

**Comment by benlikescode** [comment]
You can use the /games/{id} endpoint which returns the locations from a given game. If you have any other questions, feel free to message me on reddit or in the discord.
