### ISSUE TITLE
New home page daily tips [DISCUSSION]

### ISSUE THREAD

**Issue by benlikescode** [benlikescode/geohub#71]
I am hoping to give the daily tips on the home page a refresh. Looking to come up with 31 new tips (ideally they are between 40 - 70 characters) and aim to be a balance between beginner/advanced tips.

Can be any meta, you think is valuable (ex. ghana roof tape, holey poles, certain coverage etc...)

Comment any tips you would like to see and upvote others if they are good!

**Comment by oxedom** [comment]
Pay attention to what side of the road you are driving on!

**Comment by tabishnaqvi1311** [comment]
If you see yellow lines on the road, you are probably in the States.
