### ISSUE TITLE
"Missing distance unit" when adding Google API key

### ISSUE THREAD

**Issue by adnan-smlatic** [benlikescode/geohub#80]
I've tried adding my own Google api key but just get the "Missing distance unit." when clicking Save changes. 

Even though the distance unit is preselected by default

Other than that, Ben, you're one beautiful human, much respect to you for making this. Geoguesser went all greedy and corporate and it's impossible to play anymore

**Comment by oxedom** [comment]
Same issue, fixed it by toogling the distance unit select bar.
