### ISSUE TITLE
bug: The street view is in negative colors

### ISSUE THREAD

**Issue by NoneTsotsi** [benlikescode/geohub#88]
![Screenshot_20240220_154814_Chrome](https://github.com/benlikescode/geohub/assets/142915815/2ad7aa8d-e7a9-4216-a929-e48f7c789acf)
There is problem on my samsung with colors in street view, how do i fix that?
(Im on Samsung A34, browser is Google Chrome)

**Comment by komarvtdP** [comment]
Same problem occurred on my PC (Pop!OS LTS 22.04) both in Firefox (Native; 122.0.1 - 64bit) and Brave Browser (Flatpak; Version 1.61.120 Chromium: 120.0.6099.234).

**Comment by benlikescode** [comment]
Thanks for reporting this, but this is actually the expected behavior when the Google Maps API quota is reached.
